import express from "express";
import productos from "./routes/productos.js";
import pedidos from "./routes/pedidos.js";
import auth from "./routes/auth.js";
import usuarios from "./routes/usuarios.js";
import { setupCORS } from "./middleware/cors.js";
import { correlation } from "./middleware/correlation.js";
import { authContext } from "./middleware/authContext.js";
const app = express();
const CLIENT_ORIGIN = "*";
app.use(express.json());
app.use(setupCORS(CLIENT_ORIGIN));
app.use(correlation);
app.use(authContext);
app.get("/", (req, res) => res.send("API CaféCat con login, roles y registro de pedidos ✅"));
app.use("/api/productos", productos);
app.use("/api/pedidos", pedidos);
app.use("/api", auth);
app.use("/api/usuarios", usuarios);
app.listen(3000, () => console.log("API activa en http://localhost:3000"));